import type { Locale } from "@/app/locale";
import type { AboutCopy } from "@/components/about/copy";

export const aboutCopy: Record<Locale, AboutCopy> = {
  pl: {
    nameKey: "NAME",
    name: "Filip Wojno",
    locKey: "LOC",
    loc: "Szczecin, Poland",
    roleKey: "ROLE",
    role: "DEVOPS / SOFTWARE ENGINEER",
    bioLabel: "ABOUT ME",
    bio: "Pasjonat automatyzacji, homelabowania, programowania oraz wspinaczki. Zwolennik open-source, self-hostingu i dobrych gier.",
    educationLabel: "EDUCATION",
    education: [
      {
        id: "edu-1",
        school: "Zachodniopomorski Uniwersytet Technologiczny w Szczecinie",
        period: "2023 - 2027",
        description: "Teleinformatyka - Inżynier",
        bullets: [
          "Aktywny członek koła naukowego: Apacz500",
          "Członek Sejmiku Studenckiego na Wydziale Elektrycznym"
        ],
      },
      {
        id: "edu-2",
        school: "Technikum Informatyczne SCI w Szczecinie",
        period: "2019 — 2023",
        description: "Informatyka - Technik Informatyk",
        bullets: [
          "Zwycięzca szkolnego hackathonu",
          "Członek samorządu szkolnego"
        ],
      }
    ],
    workLabel: "WORK EXPERIENCE",
    workRoleLabel: "STANOWISKO",
    workCompanyLabel: "FIRMA",
    workPeriodLabel: "OKRES",
    workDescriptionLabel: "ZAKRES OBOWIĄZKÓW",
    workSkillsLabel: "STACK",
    work: [
      {
        id: "job-1",
        role: "Working Student",
        company: "Nokia Solutions and Networks",
        period: "2026 — aktualnie",
        bullets: [
          "Full-stack: nowe funkcje w Flask (Python) i ReactJS.",
          "AI w workflow: Cursor, GitHub Copilot, własne agent skills i reguły.",
          "Code review: przeglądy kodu zespołu przed wdrożeniem.",
          "DevOps: dashboardy w Grafanie na danych z Prometheusa, konfiguracja jobów w Jenkinsie, playbooki Ansible.",
          "Rozwój systemów: nowe funkcjonalności i optymalizacja wydajności.",
          "Wersjonowanie: Gerrit i GitLab.",
        ],
        skills: [
          "Python",
          "Flask",
          "Swagger",
          "ReactJS",
          "TailwindCSS",
          "TypeScript",
          "MongoDB",
          "Redis",
          "ClickHouse",
          "Grafana",
          "Prometheus",
          "Jenkins",
          "Ansible",
          "Gerrit",
          "GitLab",
        ],
      },
      {
        id: "job-2",
        role: "Ekspert sprzedaży / Promotor produktów",
        company: "SalesUP Polska (Lenovo)",
        period: "2025 - 2026",
        bullets: [
          "Sprzedaż oraz prezentacja produktów Lenovo.",
          "Zarządzanie materiałami promocyjnymi na terenie sklepu.",
          "Zarządzanie stanami magazynowymi produktów.",
          "Komunikacja oraz negocjacje z klientami.",
        ],

      },
      {
        id: "job-3",
        role: "Data scraper",
        company: "SEOmood",
        period: "03/2023 - 05/2023",
        bullets: [
          "Skrypty w JavaScript do zbierania i przetwarzania danych ze stron (web scraping i automatyzacja).",
          "Usprawnienia i poprawki błędów w istniejącym kodzie.",
          "Modernizacja i optymalizacja legacy kodu pod wydajność i czytelność.",
        ],
        skills: [
          "JavaScript", 
          "Node.js",
          "Selenium",
          "Puppeteer",
          "Playwright",
        ],
      },
      {
        id: "job-4",
        role: "Praktykant",
        company: "Technikum informatyczne SCI w Szczecinie",
        period: "08/2021",
        bullets: [
          "Podłączanie komputerów do serwerów i stawianie nowych systemów: instalacja Windows lub Linux, zakładanie kont użytkowników z określonymi ustawieniami.",
          "Przygotowanie sal i pracowni komputerowych do lekcji: konfiguracja systemów i łączności sieciowej.",
        ],
      },
    ],
    eof: "EOF_ REACHED. WAITING FOR INPUT...",
  },
  en: {
    nameKey: "NAME",
    name: "Filip Wojno",
    locKey: "LOC",
    loc: "Szczecin, Poland",
    roleKey: "ROLE",
    role: "DEVOPS / SOFTWARE ENGINEER",
    bioLabel: "ABOUT ME",
    bio: "Passionate about automation, homelabbing, programming and climbing. Fan of open-source, self-hosting and good games.",
    educationLabel: "EDUCATION",
    education: [
      {
        id: "edu-1",
        school: "West Pomeranian University of Technology in Szczecin",
        period: "2023 - 2027",
        description: "Teleinformatics - Engineer's degree",
        bullets: [
          "Active member of the Apacz500 student research club",
          "Member of the Student Council at the Faculty of Electrical Engineering",
        ],
      },
      {
        id: "edu-2",
        school: "SCI IT Technical School in Szczecin",
        period: "2019 — 2023",
        description: "IT - IT Technician",
        bullets: [
          "Winner of the school hackathon",
          "Member of the student council",
        ],
      },
    ],
    workLabel: "WORK EXPERIENCE",
    workRoleLabel: "ROLE",
    workCompanyLabel: "COMPANY",
    workPeriodLabel: "PERIOD",
    workDescriptionLabel: "RESPONSIBILITIES",
    workSkillsLabel: "SKILLS",
    work: [
      {
        id: "job-1",
        role: "Working Student",
        company: "Nokia Solutions and Networks",
        period: "2026 — present",
        bullets: [
          "Full-stack: new features in Flask (Python) and ReactJS.",
          "AI in workflow: Cursor, GitHub Copilot, custom agent skills and rules.",
          "Code review: reviewing teammates' code before deployment.",
          "DevOps: Grafana dashboards on Prometheus data, Jenkins job configuration, Ansible playbooks.",
          "Software evolution: new functionality and performance tuning.",
          "Version control: Gerrit and GitLab.",
        ],
        skills: [
          "Python",
          "Flask",
          "Swagger",
          "ReactJS",
          "TailwindCSS",
          "TypeScript",
          "MongoDB",
          "Redis",
          "ClickHouse",
          "Grafana",
          "Prometheus",
          "Jenkins",
          "Ansible",
          "Gerrit",
          "GitLab",
        ],
      },
      {
        id: "job-2",
        role: "Sales expert / Product promoter",
        company: "SalesUP Polska (Lenovo)",
        period: "2025 - 2026",
        bullets: [
          "Selling and presenting Lenovo products.",
          "Managing promotional materials across the store.",
          "Managing product stock levels.",
          "Communication and negotiations with customers.",
        ],
      },
      {
        id: "job-3",
        role: "Data scraper",
        company: "SEOmood",
        period: "03/2023 - 05/2023",
        bullets: [
          "JavaScript scripts for collecting and processing data from websites (web scraping and automation).",
          "Improvements and bug fixes in the existing codebase.",
          "Modernizing and optimizing legacy code for performance and readability.",
        ],
        skills: [
          "JavaScript",
          "Node.js",
          "Selenium",
          "Puppeteer",
          "Playwright",
        ],
      },
      {
        id: "job-4",
        role: "Intern",
        company: "SCI IT Technical School in Szczecin",
        period: "08/2021",
        bullets: [
          "Connecting computers to servers and setting up new systems: installing Windows or Linux, creating user accounts with specific settings.",
          "Preparing classrooms and computer labs for lessons: system setup and network connectivity.",
        ],
      },
    ],
    eof: "EOF_ REACHED. WAITING FOR INPUT...",
  },
};
